PromQL DSL implemented
yoomoney/grafana-dashboard-dsl pull request #16
Opened 2021-08-30 06:06 UTC by ul8422

2021-08-30 12:23 UTC, layfe commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/panels/YAxis.kt
> +        PERCENT_0_1("percentunit"),
у prometheus еще есть например тип events
jvm_gc_collection_count_events{app_name="backend-platform",collector="G1 Old Generation",} 0.0

это в какой тип попадет сюда?

2021-08-30 12:25 UTC, layfe commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/prometheus/functions/AbsentOverTime.kt
> +package ru.yoomoney.tech.grafana.dsl.metrics.prometheus.functions
вижу пакеты
ru.yoomoney.tech.grafana.dsl.metrics.functions
и
ru.yoomoney.tech.grafana.dsl.metrics.prometheus.functions

в function общие для всех? может, сделать в functions пакет prometheus?

2021-08-30 12:27 UTC, layfe commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/AnyMetric.kt
> +interface AnyMetric {
почему понадобился интефейс AnyMetric в дополнении к Metric? Чем они отличаются?

2021-08-30 12:35 UTC, layfe commented on src/examples/kotlin/ru/yoomoney/tech/grafana/dsl/examples/GrafanaPrometheusDemoLayouts.kts
> +                    "process_failed_total[1m]".asRangeVector().avgOverTime() /
не очень нравится, что в метрику передается значение [1m] прям в строке.
может, сделать обертку для этого, для удобного указания duration?

2021-08-30 12:35 UTC, layfe approved these changes

2021-08-30 12:35 UTC, ul8422 commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/prometheus/functions/AbsentOverTime.kt
> +package ru.yoomoney.tech.grafana.dsl.metrics.prometheus.functions
- `ru.yoomoney.tech.grafana.dsl.metrics.prometheus.functions` это функции `graphite`
- с целью не мажорить либу не стал трогать этот пакет

показалось так гибче - у нас есть пакет `ru.yoomoney.tech.grafana.dsl.metrics.prometheus`, в котором лежат типы, функции, операторы, возможно что-то еще появится

2021-08-30 12:37 UTC, ul8422 commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/AnyMetric.kt
> +interface AnyMetric {
для удобства автокомплита

- для метрик `prometheus` доступны только функции `prometheus`
- если начинать наследовать или использовать интерфейс `Metric`, то все функции графита будут валидны на этапе компиляции

2021-08-30 12:38 UTC, layfe commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/prometheus/functions/AbsentOverTime.kt
> +package ru.yoomoney.tech.grafana.dsl.metrics.prometheus.functions
думаю здесь можно мажорить (уточнить), т.к. если dsl подключается локально в компонент - он в отдельной конфигурации grafanaFromDirCompile и конфликта нет

2021-08-30 12:39 UTC, ul8422 commented on src/examples/kotlin/ru/yoomoney/tech/grafana/dsl/examples/GrafanaPrometheusDemoLayouts.kts
> +                    "process_failed_total[1m]".asRangeVector().avgOverTime() /
`Duration` не уверен что удобно, т.к. как правило используются "переменные графаны"
- добавил билдер, для удобного описания `alias`-ов, `interval`-ов. Сегодня закоммичу. повторно отпишусь

2021-08-30 12:46 UTC, ul8422 commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/prometheus/functions/AbsentOverTime.kt
> +package ru.yoomoney.tech.grafana.dsl.metrics.prometheus.functions
- у нас же либа еще в опенсорсе 
- если мажорить, то предлагаю отдельно (или текущий вариант очень страшно выглядит? :) )

т.к.:
* думаю если пройтись по либе, то найдем много мелочей - контракт которых хотим поправить
* боюсь поспешить и ошибиться с удобными для всех контрактами

2021-08-30 13:51 UTC, layfe commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/AnyMetric.kt
> +interface AnyMetric {
понятно, а Metric переименовать из за мажора не хочешь?

2021-08-30 13:52 UTC, layfe commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/prometheus/functions/AbsentOverTime.kt
> +package ru.yoomoney.tech.grafana.dsl.metrics.prometheus.functions
ок, не, нормально выглядит

2021-08-30 14:42 UTC, ul8422 commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/AnyMetric.kt
> +interface AnyMetric {
ага

2021-08-30 14:54 UTC, ul8422 commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/panels/YAxis.kt
> +        PERCENT_0_1("percentunit"),
Как я понял, `_events` ~пришел из [micrometer](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/BaseUnits.java)

если правильно понимаю, то это `short` (аналогично `thread_count`)

2021-08-30 14:58 UTC, ul8422 commented on src/examples/kotlin/ru/yoomoney/tech/grafana/dsl/examples/GrafanaPrometheusDemoLayouts.kts
> +                    "process_failed_total[1m]".asRangeVector().avgOverTime() /
добавил

2021-08-31 09:28 UTC, f0y requested changes

2021-08-31 09:28 UTC, f0y commented on CHANGELOG.md
> +* PromQL DSL implemented
Что поменялось? Что добавлено?

2021-08-31 09:28 UTC, f0y commented on src/examples/kotlin/ru/yoomoney/tech/grafana/dsl/examples/GrafanaGraphiteDemoLayouts.kts
> +                    metrics(Graphite) {
это обратно совместимые изменения?

2021-08-31 09:28 UTC, f0y commented on README.md
> +* Graphite
не вижу ссылки на example

2021-08-31 09:28 UTC, f0y commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/MetricsBuilder.kt
> +    @Deprecated("Use function `prometheusMetric` instead. That supports DSL. Pay attention to `instant` default value")
это можно удалить? Не думаю что кто уже использует

2021-08-31 09:36 UTC, ul8422 commented on src/examples/kotlin/ru/yoomoney/tech/grafana/dsl/examples/GrafanaGraphiteDemoLayouts.kts
> +                    metrics(Graphite) {
да. для графита оба варианта (`metrics {...}` и `metrics(Graphite) { ... }`) корректны

2021-09-01 17:42 UTC, layfe commented on src/main/kotlin/ru/yoomoney/tech/grafana/dsl/metrics/MetricsBuilder.kt
> +    @Deprecated("Use function `prometheusMetric` instead. That supports DSL. Pay attention to `instant` default value")
удалила

2021-09-01 17:43 UTC, layfe commented on README.md
> +* Graphite
добавила пути к example

2021-09-01 17:43 UTC, layfe commented on CHANGELOG.md
> +* PromQL DSL implemented
расширила описание

2021-09-01 17:45 UTC, f0y approved these changes

2021-09-01 17:47 UTC, merged